title: Kalkin's Blog

permalink: /:year/:month/:day/:title/

url: http://www.kalkinblog.tk

# Use kramdown as markdown parser engine.
markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md

kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'id-'
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

gems:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7

author:
    name: kalkin7
    twitter: https://twitter.com/kalkin_7
    email: kalkin7@gmail.com

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]

exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'CNAME', 'node_modules', 'gulpfile.js', 'package.json', 'new_tag.bat', 'git_push.bat', 'git_link_update.bat', 'git_blog_update.bat', 'git_pull.bat', 'jekyll watch.bat' ]