title: Kalkin's Blog

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

permalink: /:year/:month/:day/:title/

url: http://www.kalkinblog.tk

# Use kramdown as markdown parser engine.
markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']

gems:
  - jekyll-paginate
  - jekyll-sitemap

timezone: Asia/Seoul

paginate: 10

author:name:
    name: kalkin7
    twitter: https://twitter.com/kalkin_7
    email: kalkin7@gmail.com

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]

exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'CNAME', 'node_modules', 'gulpfile.js', 'package.json', 'new_tag.bat', 'git_push.bat', 'git_link_update.bat', 'git_blog_update.bat', 'git_pull.bat', 'jekyll watch.bat' ]